### ISSUE TITLE
highlight exist on page but not displayed on comment pane

### ISSUE THREAD

**Issue by n0vakovic** [jasust/issues#1]
On https://campfirelabs.co/blog-1/2019/1/10/how-i-built-a-5000-per-month-side-project I've added highlight and posted it. Icon shows there's a highlight on this page. After Page Init, comment pane is displayed, highlight is not visible

**Comment by jasust** [comment]
The problem is no longer relevant for version 1.40 and above. If something similar occurs again, feel free to reopen the issue.
