### ISSUE TITLE
bad rendering after page init

### ISSUE THREAD

**Issue by n0vakovic** [jasust/issues#2]
URL: http://nymag.com/intelligencer/2018/12/how-much-of-the-internet-is-fake.html
After Page Init, web page looks weird

**Comment by jasust** [comment]
Fixed in the next update for that and similar pages with the same cause. 
Still not looking great for some pages like: [https://stackoverflow.com/](https://stackoverflow.com/)

**Comment by jasust** [comment]
The problem is no longer relevant for version 1.40 and above. If something similar occurs again, feel free to reopen the issue.
